### ISSUE TITLE
Convert Shell Scripts to Playbook and include them all in single main playbook

### ISSUE THREAD

**Issue by trishnaguha** [trishnaguha/build-atomic-host#8]
@gbraad gave the idea to convert all shell scripts to playbooks and include all the playbooks in one single playbook, for instance `main.yml` in order to achieve automate all the things.

**Comment by gbraad** [comment]
Some additional changes are needed to have a single playbook. But almost there... already looks a whole lot better.

**Comment by trishnaguha** [comment]
Yeah we need `create-vm` playbook :-).

**Comment by gbraad** [comment]
@trishnaguha there might be libvirt support, but in your shell scripts you use `virt-install` IIRC. Not sure if people have abstracted that just yet. This might be an improvement for the future...

**Comment by gbraad** [comment]
@trishnaguha also, do not forget to update the README

**Comment by trishnaguha** [comment]
@gbraad I won't :-).

**Comment by gbraad** [comment]
@trishnaguha "won't do" or "won't forget"... :-/

**Comment by trishnaguha** [comment]
@gbraad Haha "won't forget". Doing it now only :-P
